### ISSUE TITLE
Support Webpack

### ISSUE THREAD

**Issue by Vaccano** [Vheissu/Aurelia-Configuration#55]
I tried to install this plugin into the Aurelia Webpack Typescript Skeleton, and when I run I get the following error:

     ERROR in ./~/aurelia-configuration/dist/commonjs/index.js
     Module not found: Error: Can't resolve './aurelia-configuration' in 'C:\my\project\node_modules\aurelia-configuration\dist\commonjs'
     @ ./~/aurelia-configuration/dist/commonjs/index.js 7:28-62

It seems that this line: `var _aureliaConfiguration = require('./aurelia-configuration');` in `aurelia-configuration/dist/commonjs/index.js` is being interpreted as a webpack require (I think).

I am not sure if there is a way around this, but I would love to use this plugin.

**Comment by Vheissu** [comment]
Webpack support is definitely coming. I am in the process of restructuring my plugin structures because this and others are getting hard and time consuming to maintain. I am going to be using CI, so releases are easier to put out.

**Comment by mikeesouth** [comment]
Any update on this? I'm also eagerly waiting for webpack support :)
Great job with the lib @Vheissu!

**Comment by Vheissu** [comment]
The latest release should fix this.

```
npm install aurelia-configuration --save
```

**Comment by mikeesouth** [comment]
@Vheissu Thanks, looks good but I'm still getting an error:
```
C:\projects\foo\node_modules\aurelia-configuration\dist\index.d.ts:1:27
    Cannot find module './configure'.
```

In index.d.ts (here: https://github.com/Vheissu/Aurelia-Configuration/blob/master/dist/index.d.ts) there is an import of `./configure` but there is no such file.
